FIND_PATH(SDL2_TTF_INCLUDE_DIR NAMES SDL2/SDL_ttf.h)
MARK_AS_ADVANCED(SDL2_TTF_INCLUDE_DIR)
 
FIND_LIBRARY(SDL2_TTF_LIBRARY NAMES
  SDL2_ttf
  libSDL2_ttf)
MARK_AS_ADVANCED(SDL2_TTF_LIBRARY)
 
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS (
  SDL2_ttf DEFAULT_MSG
  SDL2_TTF_LIBRARY
  SDL2_TTF_INCLUDE_DIR)
