FIND_PATH(SDL2_IMAGE_INCLUDE_DIR NAMES SDL2/SDL_image.h)
MARK_AS_ADVANCED(SDL2_IMAGE_INCLUDE_DIR)
 
FIND_LIBRARY(SDL2_IMAGE_LIBRARY NAMES
  SDL2_image
  libSDL2_image)
MARK_AS_ADVANCED(SDL2_IMAGE_LIBRARY)
 
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS (
  SDL2_image DEFAULT_MSG
  SDL2_IMAGE_LIBRARY
  SDL2_IMAGE_INCLUDE_DIR)
